#!/bin/sh

set -x

CURR_DIR="$(pwd)"

# Get spread
export SPREAD_DIR="$CURR_DIR/bin"
mkdir -p bin
( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )

# Prepare spread-images project
export SPREAD_IMAGES_DIR="$CURR_DIR/target"
git clone https://github.com/sergiocazzolato/spread-images "$CURR_DIR/spread-images"
( cd "$CURR_DIR/spread-images" && git checkout adaptation-for-spread-cron-integration )
mv sa.json "$CURR_DIR/spread-images/sa.json"

# Prepare snapd project
export SNAPD_DIR="$CURR_DIR/target"
git clone https://github.com/snapcore/snapd.git "$CURR_DIR/snapd"

# Checkout to last_build_number
. ./options
last_build_number=$(echo "$TRAVIS_COMMIT_MESSAGE" | perl -n -e '/'"$message"' \((.*?)\)/ && print $1' | cut -d+ -f1 | cut -d~ -f1)
git checkout "${last_build_number}"

# Install gcloud sdk and login into GCE using google account
export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update && sudo apt-get install google-cloud-sdk
gcloud auth activate-service-account --key-file="$SPREAD_IMAGES_DIR/sa.json" --project computeengine

export TASK=update-ubuntu-16.04-64

# run spread-images task
cd "$CURR_DIR"
cp -rf "$CURR_DIR/spread-images" "$CURR_DIR/target"
cd "$CURR_DIR/target"
. "$CURR_DIR/spread-images/google_task.sh"
get_env_for_task_google "$TASK"
run_spread_images "$TASK"

# run snapd tests
cd "$CURR_DIR"
rm -rf "$CURR_DIR/target"
cp -rf "$CURR_DIR/snapd" "$CURR_DIR/target"
. "$CURR_DIR/spread-images/google_task.sh"
cd "$CURR_DIR/target"
get_env_for_task_google "$TASK"
run_snapd "$TASK"
