#!/bin/sh
set -e

mkdir -p bin
( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )
git clone https://github.com/snapcore/snapd target

cd target

export SPREAD_NEW_CORE_CHANNEL=edge

# unity test is failing, only run docker
../bin/spread -v google:tests/nightly/ google-nested:ubuntu-16.04-64:tests/nested/classic/ google-nested:ubuntu-18.04-64:tests/nested/classic/ google-nested:ubuntu-16.04-64:tests/nested/core/ google-nested:ubuntu-18.04-64:tests/nested/core/
